# Generated by Django 2.2 on 2019-04-09 10:55

import database.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='品牌名称')),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('origin', models.CharField(max_length=30, null=True, verbose_name='产地')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '上架'), (2, '下架'), (3, '促销'), (4, '预售')], default=1, verbose_name='产品销售状态')),
                ('inventory', models.PositiveIntegerField(default=0, verbose_name='商品库存')),
                ('sales', models.PositiveIntegerField(default=0, verbose_name='商品销量')),
                ('comment_num', models.PositiveIntegerField(default=0, verbose_name='评论数量')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Brand', verbose_name='关联品牌')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_portrait', models.ImageField(upload_to='user/head_portrait/')),
                ('cell_phone', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('sex', models.PositiveSmallIntegerField(choices=[(1, '男'), (0, '女'), (2, '密')], verbose_name='性别')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('wechat', models.CharField(max_length=20, null=True, verbose_name='微信')),
                ('qq', models.CharField(max_length=15, null=True, verbose_name='QQ')),
                ('msn', models.CharField(max_length=20, null=True, verbose_name='MSN')),
                ('work_unit', models.CharField(max_length=50, null=True, verbose_name='工作单位')),
                ('family_address', models.CharField(max_length=50, null=True, verbose_name='家庭住址')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='账户余额')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd', models.CharField(max_length=20, verbose_name='交易单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='交易金额')),
                ('trding_hour', models.CharField(max_length=30, verbose_name='交易时间戳')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, database.models.TimeTransition),
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品规格全称')),
                ('describe', models.CharField(max_length=20, verbose_name='规格描述')),
                ('integral', models.PositiveSmallIntegerField(default=0, verbose_name='商品积分')),
                ('mall_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商城价')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='市场价')),
                ('inventory', models.PositiveIntegerField(default=0, verbose_name='该规格商品的库存数量')),
                ('sales_volume', models.PositiveIntegerField(default=0, verbose_name='该规格商品的销量')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Commodity', verbose_name='关联商品')),
            ],
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='收货名')),
                ('cell_phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('postal_code', models.CharField(max_length=6, null=True, verbose_name='邮政编码')),
                ('province', models.CharField(max_length=20, null=True, verbose_name='省')),
                ('city', models.CharField(max_length=20, null=True, verbose_name='市')),
                ('district', models.CharField(max_length=20, null=True, verbose_name='区/县/乡镇')),
                ('detailed', models.CharField(max_length=150, verbose_name='详细地址')),
                ('phone', models.CharField(max_length=30, null=True, verbose_name='固定电话')),
                ('is_default', models.BooleanField(default=0, verbose_name='默认地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=25, verbose_name='订单编号')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '待支付'), (2, '代发货'), (3, '待收货'), (4, '已收货'), (5, '已确认'), (6, '已完成'), (0, '已取消')], verbose_name='订单状态')),
                ('order_time', models.CharField(max_length=30, verbose_name='下单时间戳')),
                ('delivery_time', models.CharField(max_length=30, null=True, verbose_name='发货时间戳')),
                ('receipt_time', models.CharField(max_length=30, null=True, verbose_name='收货时间戳')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='邮费')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='订单总价')),
                ('paymode', models.PositiveSmallIntegerField(choices=[(1, '余额支付'), (2, '支付宝支付'), (3, '微信支付'), (4, '银联支付'), (5, '广发银行')], verbose_name='支付方式')),
                ('address', models.CharField(max_length=150, verbose_name='省/市/区')),
                ('detailed', models.CharField(max_length=150, verbose_name='详细地址')),
                ('is_self', models.BooleanField(default=0, verbose_name='是否自提')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, database.models.TimeTransition),
        ),
        migrations.CreateModel(
            name='OrderCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='商品的选购数量，默认为1')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品小计总价')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.Commodity')),
                ('orderform', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.OrderForm')),
            ],
        ),
        migrations.CreateModel(
            name='CommodityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commodity/infoimage/', verbose_name='商品信息图片')),
                ('is_show', models.BooleanField(default=1, verbose_name='是否为展示图片')),
                ('num', models.PositiveSmallIntegerField(verbose_name='图片编号')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Commodity', verbose_name='关联商品')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=30, verbose_name='评论时间戳')),
                ('content', models.CharField(max_length=150, verbose_name='评论内容')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Commodity', verbose_name='关联商品')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Comment', verbose_name='关联回复')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.UserProfile', verbose_name='关联用户')),
            ],
            bases=(models.Model, database.models.TimeTransition),
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.Commodity', verbose_name='关联商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('desc', models.CharField(max_length=50, verbose_name='分类描述')),
                ('is_root', models.BooleanField(default=False, verbose_name='是否是一级分类')),
                ('image', models.ImageField(blank=True, null=True, upload_to='commodity/category/', verbose_name='分类图片')),
                ('is_abort', models.BooleanField(default=False, verbose_name='是否删除')),
                ('parent', models.ForeignKey(blank=True, default=0, limit_choices_to={'is_abort': False, 'is_root': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='database.Category', verbose_name='上级分类')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='购买数量')),
                ('commodity', models.ManyToManyField(to='database.Specification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
