# Generated by Django 2.2 on 2019-04-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Category', verbose_name='关联商品分类'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Brand', verbose_name='关联商品品牌'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '上架'), (2, '下架'), (3, '促销'), (4, '预售')], default=1, verbose_name='商品销售状态'),
        ),
    ]
